"""
quanta.config — SDK configuration and credential management.

Manages backend credentials for IBM Quantum, IonQ, and Google Quantum.
Configuration is stored in TOML format at ~/.quanta/config.toml.

Example:
    >>> from quanta.config import QuantaConfig
    >>> config = QuantaConfig.load()
    >>> config.set("ibm", "api_key", "your-token")
    >>> config.save()
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path

__all__ = ["QuantaConfig", "get_config_dir", "get_system_memory_gb", "get_max_dense_qubits"]


def get_system_memory_gb() -> float:
    """Returns detected total system RAM in gigabytes."""
    try:
        return (os.sysconf("SC_PAGE_SIZE") * os.sysconf("SC_PHYS_PAGES")) / (1024**3)
    except Exception:
        return 16.0


def get_max_dense_qubits() -> int:
    """Determines maximum safe qubits for dense statevector simulation.

    Scales dynamically with available system RAM:
      - >= 44 GB (e.g. Apple Silicon M5 Pro 48GB): up to 30 qubits (~16 GB state)
      - >= 28 GB (e.g. 32GB RAM): up to 29 qubits (~8 GB state)
      - >= 14 GB (e.g. 16GB RAM): up to 28 qubits (~4 GB state)
      - < 14 GB: up to 26 qubits (~1 GB state)

    Can be overridden with QUANTA_MAX_QUBITS environment variable.
    """
    if "QUANTA_MAX_QUBITS" in os.environ:
        try:
            return int(os.environ["QUANTA_MAX_QUBITS"])
        except ValueError:
            pass

    ram_gb = get_system_memory_gb()
    if ram_gb >= 44.0:
        return 30
    if ram_gb >= 28.0:
        return 29
    if ram_gb >= 14.0:
        return 28
    return 26



def get_config_dir() -> Path:
    """Returns the Quanta config directory (~/.quanta/).

    Creates the directory if it doesn't exist.
    """
    config_dir = Path(os.environ.get("QUANTA_CONFIG_DIR", "~/.quanta")).expanduser()
    config_dir.mkdir(parents=True, exist_ok=True)
    return config_dir


def _config_path() -> Path:
    return get_config_dir() / "config.toml"


@dataclass
class QuantaConfig:
    """SDK configuration manager.

    Stores backend credentials and SDK preferences in TOML format.

    Attributes:
        backends: Dict of backend → {key: value} credential mappings.
        defaults: Default SDK settings.
    """

    backends: dict[str, dict[str, str]] = field(default_factory=dict)
    defaults: dict[str, str] = field(default_factory=dict)

    @classmethod
    def load(cls) -> QuantaConfig:
        """Loads config from ~/.quanta/config.toml.

        Returns empty config if file doesn't exist.
        """
        path = _config_path()
        if not path.exists():
            return cls()

        config = cls()
        current_section = None

        for line in path.read_text().strip().split("\n"):
            line = line.strip()
            if not line or line.startswith("#"):
                continue

            # Section header: [backends.ibm] or [defaults]
            if line.startswith("[") and line.endswith("]"):
                section = line[1:-1]
                if section.startswith("backends."):
                    backend_name = section.split(".", 1)[1]
                    config.backends.setdefault(backend_name, {})
                    current_section = ("backends", backend_name)
                elif section == "defaults":
                    current_section = ("defaults",)
                else:
                    current_section = None
                continue

            # Key-value: key = "value"
            if "=" in line and current_section:
                key, _, val = line.partition("=")
                key = key.strip()
                val = val.strip().strip('"').strip("'")

                if current_section[0] == "backends":
                    config.backends[current_section[1]][key] = val
                elif current_section[0] == "defaults":
                    config.defaults[key] = val

        return config

    def save(self) -> Path:
        """Saves config to ~/.quanta/config.toml.

        Returns:
            Path to the saved config file.
        """
        lines: list[str] = [
            "# Quanta SDK Configuration",
            "# Generated by quanta.config",
            "",
        ]

        # Defaults section
        if self.defaults:
            lines.append("[defaults]")
            for key, val in sorted(self.defaults.items()):
                lines.append(f'{key} = "{val}"')
            lines.append("")

        # Backend sections
        for backend, creds in sorted(self.backends.items()):
            lines.append(f"[backends.{backend}]")
            for key, val in sorted(creds.items()):
                # Mask sensitive values in comments
                lines.append(f'{key} = "{val}"')
            lines.append("")

        path = _config_path()
        path.write_text("\n".join(lines) + "\n")
        return path

    def set(self, backend: str, key: str, value: str) -> None:
        """Set a credential for a backend.

        Args:
            backend: Backend name (e.g., "ibm", "ionq", "google").
            key: Credential key (e.g., "api_key", "project_id").
            value: Credential value.

        Example:
            >>> config.set("ibm", "api_key", "your-token")
        """
        self.backends.setdefault(backend, {})[key] = value

    def get(self, backend: str, key: str, default: str = "") -> str:
        """Get a credential for a backend.

        Args:
            backend: Backend name.
            key: Credential key.
            default: Default value if not found.
        """
        return self.backends.get(backend, {}).get(key, default)

    def set_default(self, key: str, value: str) -> None:
        """Set a default SDK preference."""
        self.defaults[key] = value

    def get_default(self, key: str, default: str = "") -> str:
        """Get a default SDK preference."""
        return self.defaults.get(key, default)

    def list_backends(self) -> list[str]:
        """List configured backend names."""
        return list(self.backends.keys())

    def describe(self) -> str:
        """Human-readable config summary (credentials masked)."""
        lines = ["Quanta SDK Configuration", "=" * 40]

        if self.defaults:
            lines.append("\n[defaults]")
            for key, val in self.defaults.items():
                lines.append(f"  {key} = {val}")

        for backend, creds in self.backends.items():
            lines.append(f"\n[backends.{backend}]")
            for key, val in creds.items():
                masked = val[:4] + "***" + val[-4:] if len(val) > 12 else "***"
                lines.append(f"  {key} = {masked}")

        if not self.backends:
            lines.append("\nNo backends configured.")
            lines.append("Use: config.set('ibm', 'api_key', 'your-token')")

        return "\n".join(lines)

    def __repr__(self) -> str:
        backends = list(self.backends.keys())
        return f"QuantaConfig(backends={backends})"
